name: CI

on: [push, pull_request]

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 7
        platform: x64       
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y clang-format build-essential autoconf automake libtool cmake lcov libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev
    - name: Install RocksDB
      run: sudo apt-get update && sudo apt-get install librocksdb-dev
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make -j4
    - name: Run Main
      run: |
        ./build/gtest_example_tests.cc

  test-sanitizer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov

